version: '3.8'
services:
  gateway:
    build:
      context: shareIt-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
      context: shareIt-server
    container_name: server
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe

  db:
    image: postgres:16
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe